---
- name: Install Docker and Run Container
  hosts: all
  become: yes
  remote_user: ubuntu

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install pip3
      package:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt cache (after adding Docker repository)
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Log in to Docker repository
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Pull Docker image
      docker_image:
        name: "diamond0816/learnings:latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: my_container
        image: "diamond0816/learnings:latest"
        ports:
          - "8090:80"
        state: started